/**
 * Invertebrate species: jellies and siphonophores, vent shrimp and hadal
 * amphipods, benthic crawlers, rooted corals, anemones, sea lilies and
 * tube worms, and the cephalopods. Sizes follow docs/research/species.md;
 * `visScale` lifts the smallest animals so they read in the lights.
 */

import { def } from './defs.js';
import type { SpeciesDef } from './types.js';

export const INVERTEBRATES: SpeciesDef[] = [
  // ---- midwater drifters ----
  def({
    id: 'nanomia',
    common: 'Common siphonophore',
    scientific: 'Nanomia bijuga',
    group: 'Jellies',
    archetype: 'drifter',
    model: 'siphonophore',
    size: 0.3,
    depth: [100, 800],
    speed: [0.04, 0.22],
    anim: 'chain',
    amp: 0.07,
    freq: 2.2,
    glow: 'flash',
    glowColor: 0x6fdcff,
    maxCount: 24,
    scanRadius: 14,
    look: { translucent: 0.42 },
  }),
  def({
    id: 'atolla',
    common: 'Crown jelly',
    scientific: 'Atolla wyvillei',
    group: 'Jellies',
    archetype: 'drifter',
    model: 'medusa',
    size: 0.14,
    depth: [350, 4000],
    speed: [0.05, 0.3],
    glow: 'flash',
    glowColor: 0x3f9bff,
    maxCount: 22,
    scanRadius: 14,
    look: {
      H: 0.62,
      cBell: 0x8a1428,
      cRim: 0x5e0c1c,
      cCanal: 0x4e0b17,
      cGonad: 0xc03540,
      cArm: 0x7a1020,
      cTent: 0xa51c2e,
      canals: 12,
      lobes: 20,
      arms: 0,
      tent: 1,
      tentLen: 2.4,
      glowRim: 1,
      gonad: 0,
      translucent: 0.62,
    },
  }),
  def({
    id: 'comb-jelly',
    common: 'Lobate comb jelly',
    scientific: 'Bolinopsis infundibulum',
    group: 'Jellies',
    archetype: 'drifter',
    model: 'comb',
    size: 0.12,
    depth: [8, 1200],
    speed: [0.03, 0.2],
    anim: 'comb',
    amp: 0.04,
    freq: 2,
    glow: 'steady',
    glowColor: 0x8fe0ff,
    maxCount: 28,
    scanRadius: 12,
    look: { tintGlow: true, translucent: 0.35 },
  }),

  // ---- small vent swimmers and hadal scavengers ----
  def({
    id: 'beebe-shrimp',
    common: 'Beebe vent shrimp',
    scientific: 'Rimicaris hybisae',
    group: 'Crustaceans',
    archetype: 'swarm',
    model: 'shrimp',
    size: 0.045,
    depth: [4600, 5100],
    altitude: [0.1, 2.2],
    speed: [0.05, 0.6],
    maxCount: 140,
    scanRadius: 9,
    look: { cBody: 0xf2e6d4, cDark: 0xc9a98f, translucent: 0.75 },
  }),
  def({
    id: 'hawaii-shrimp',
    common: 'Hawaiʻi vent shrimp',
    scientific: 'Opaepele loihi',
    group: 'Crustaceans',
    archetype: 'swarm',
    model: 'shrimp',
    size: 0.03,
    depth: [900, 1250],
    altitude: [0.1, 1.6],
    speed: [0.05, 0.7],
    maxCount: 120,
    scanRadius: 9,
    look: { cBody: 0xf4d9c6, cDark: 0xd18f78, translucent: 0.7 },
  }),
  def({
    id: 'hadal-amphipod',
    common: 'Giant hadal amphipod',
    scientific: 'Hirondellea gigas',
    group: 'Crustaceans',
    archetype: 'swarm',
    model: 'shrimp',
    size: 0.04,
    depth: [8000, 11000],
    altitude: [0.05, 1.2],
    speed: [0.04, 0.5],
    attract: 0.6,
    maxCount: 110,
    scanRadius: 9,
    look: { kind: 'amphipod', cBody: 0xf0e6d6, cDark: 0xc7ab8f, translucent: 0.8 },
  }),

  // ---- benthic crawlers ----
  def({
    id: 'sun-star',
    common: 'California sun star',
    scientific: 'Rathbunaster californicus',
    group: 'Echinoderms',
    archetype: 'crawler',
    model: 'star',
    size: 0.38,
    depth: [150, 1050],
    anim: 'crawl',
    amp: 0.03,
    maxCount: 40,
    scanRadius: 10,
    look: { arms: 14, disc: 0.15, armW: 0.034, flat: 0.5, cA: 0xe0a470, cB: 0xa86a3c },
  }),
  def({
    id: 'brittle-star',
    common: 'Armed brittle star',
    scientific: 'Ophiosphalma armigerum',
    group: 'Echinoderms',
    archetype: 'crawler',
    model: 'star',
    size: 0.16,
    depth: [3400, 4900],
    maxCount: 60,
    scanRadius: 9,
    look: { arms: 5, disc: 0.1, armW: 0.026, flat: 0.4, serp: 0.7, cA: 0xe8dfcf, cB: 0xb4a690 },
  }),
  def({
    id: 'long-tailed-cucumber',
    common: 'Purple long-tailed sea cucumber',
    scientific: 'Psychropotes buglossa',
    group: 'Echinoderms',
    archetype: 'crawler',
    model: 'cucumber',
    size: 0.22,
    depth: [3500, 5600],
    speed: [0.01, 0.05],
    maxCount: 36,
    scanRadius: 10,
    look: { W: 0.2, Hh: 0.15, sail: 0.42, papillae: 14, cD: 0x7a3b7b, cB: 0xb78ab3 },
  }),
  def({
    id: 'amperima',
    common: 'Pink sea cucumber',
    scientific: 'Amperima rosea',
    group: 'Echinoderms',
    archetype: 'crawler',
    model: 'cucumber',
    size: 0.1,
    depth: [3500, 5600],
    speed: [0.01, 0.06],
    maxCount: 40,
    scanRadius: 9,
    look: { W: 0.22, Hh: 0.16, sail: 0, papillae: 10, cD: 0xd68a98, cB: 0xeab9c0 },
  }),
  def({
    id: 'squat-lobster',
    common: 'Deep-sea squat lobster',
    scientific: 'Munidopsis sp.',
    group: 'Crustaceans',
    archetype: 'crawler',
    model: 'lobster',
    size: 0.08,
    depth: [2400, 5100],
    speed: [0.02, 0.12],
    maxCount: 36,
    scanRadius: 9,
    look: { cA: 0xf1ece2, cB: 0xd8ad90 },
  }),

  // ---- rooted animals ----
  def({
    id: 'tubeworm',
    common: 'Juan de Fuca tubeworm',
    scientific: 'Ridgeia piscesae',
    group: 'Worms',
    archetype: 'sessile',
    model: 'tubeworm',
    size: 0.55,
    depth: [1400, 1700],
    amp: 0.07,
    freq: 1.2,
    maxCount: 130,
    scanRadius: 11,
    look: { tubes: 22, cTube: 0xece6da, cPlume: 0xc8141a },
  }),
  def({
    id: 'cold-water-coral',
    common: 'Reef-building cold-water coral',
    scientific: 'Desmophyllum pertusum',
    group: 'Corals',
    archetype: 'sessile',
    model: 'gorgonian',
    size: 0.9,
    depth: [500, 1000],
    amp: 0.008,
    freq: 0.6,
    maxCount: 120,
    scanRadius: 13,
    look: { kind: 'fan', thick: 2.6, fans: 4, moreLevels: 1, cStem: 0xe6dfcd, cPolyp: 0xf3eee1 },
  }),
  def({
    id: 'brain-coral',
    common: 'Symmetrical brain coral',
    scientific: 'Pseudodiploria strigosa',
    group: 'Corals',
    archetype: 'sessile',
    model: 'coral',
    size: 0.7,
    depth: [1, 40],
    anim: 'still',
    maxCount: 80,
    scanRadius: 12,
    look: { cA: 0xb08c55, cB: 0x6a4d2c },
  }),
  def({
    id: 'golden-coral',
    common: 'Golden coral',
    scientific: 'Chrysogorgia geniculata',
    group: 'Corals',
    archetype: 'sessile',
    model: 'gorgonian',
    size: 0.7,
    depth: [1000, 4000],
    amp: 0.06,
    freq: 0.8,
    maxCount: 90,
    scanRadius: 12,
    look: { kind: 'spiralPolyps', cStem: 0xd7b25c, cPolyp: 0xf1d98c },
  }),
  def({
    id: 'deep-coral',
    common: 'Bubblegum coral',
    scientific: 'Paramuricea sp.',
    group: 'Corals',
    archetype: 'sessile',
    model: 'gorgonian',
    size: 0.7,
    depth: [350, 1800],
    amp: 0.05,
    freq: 0.8,
    maxCount: 90,
    scanRadius: 12,
    look: { kind: 'fan', cStem: 0xd7683f, cPolyp: 0xf2a17b },
  }),
  def({
    id: 'sea-pen',
    common: 'Sea pen',
    scientific: 'Umbellula lindahli',
    group: 'Corals',
    archetype: 'sessile',
    model: 'seapen',
    size: 1,
    depth: [350, 3700],
    amp: 0.05,
    freq: 0.7,
    maxCount: 60,
    scanRadius: 12,
    look: { cStalk: 0xe9c7c4, cPolyp: 0xf2a6a8 },
  }),
  def({
    id: 'anemone',
    common: 'White sea anemone',
    scientific: 'Actiniaria sp.',
    group: 'Anemones',
    archetype: 'sessile',
    model: 'anemone',
    size: 0.12,
    depth: [500, 5100],
    amp: 0.1,
    freq: 1.1,
    maxCount: 110,
    scanRadius: 9,
    look: { cCol: 0xf2efe6, cTent: 0xfaf7ee },
  }),
  def({
    id: 'sea-lily',
    common: 'Sea lily',
    scientific: 'Crinoidea sp.',
    group: 'Echinoderms',
    archetype: 'sessile',
    model: 'crinoid',
    size: 0.28,
    depth: [800, 4000],
    amp: 0.06,
    freq: 0.9,
    maxCount: 60,
    scanRadius: 10,
    look: { cStalk: 0xe6d27a, cArm: 0xf0dc74, arms: 10, stalk: 0.55 },
  }),
  def({
    id: 'glass-sponge',
    common: 'Glass sponge',
    scientific: 'Hexactinellida sp.',
    group: 'Sponges',
    archetype: 'sessile',
    model: 'sponge',
    size: 0.28,
    depth: [800, 5000],
    anim: 'still',
    maxCount: 70,
    scanRadius: 10,
    look: { cSp: 0xf4f2ea },
  }),

  // ---- cephalopods ----
  def({
    id: 'deepwater-octopus',
    common: 'Deepwater octopus',
    scientific: 'Graneledone verrucosa',
    group: 'Cephalopods',
    archetype: 'cephalopod',
    model: 'octopus',
    size: 0.4,
    depth: [300, 3200],
    altitude: [0.2, 2.5],
    speed: [0.05, 0.8],
    maxCount: 5,
    scanRadius: 16,
    look: { cBody: 0xa5483a, cWeb: 0xb55a48, ears: 0, warts: 1, armLen: 0.62 },
  }),
  def({
    id: 'dumbo-octopus',
    common: 'Dumbo octopus',
    scientific: 'Grimpoteuthis sp.',
    group: 'Cephalopods',
    archetype: 'cephalopod',
    model: 'octopus',
    size: 0.3,
    depth: [1000, 5200],
    altitude: [0.4, 5],
    speed: [0.05, 0.55],
    maxCount: 4,
    scanRadius: 16,
    look: { cBody: 0xe9c8c2, cWeb: 0xf1d6d0, ears: 1, armLen: 0.55 },
  }),
  def({
    id: 'vampire-squid',
    common: 'Vampire squid',
    scientific: 'Vampyroteuthis infernalis',
    group: 'Cephalopods',
    archetype: 'cephalopod',
    model: 'vampire',
    size: 0.2,
    depth: [500, 1500],
    speed: [0.05, 0.6],
    glow: 'photophores',
    glowColor: 0x5fb0ff,
    maxCount: 4,
    scanRadius: 14,
    look: {},
  }),
  def({
    id: 'giant-squid',
    common: 'Giant squid',
    scientific: 'Architeuthis dux',
    group: 'Cephalopods',
    archetype: 'cruiser',
    model: 'squid',
    size: 9,
    depth: [300, 1400],
    speed: [0.3, 1.6],
    skittish: 0,
    attract: 0.35,
    anim: 'ceph',
    amp: 0.05,
    freq: 1.6,
    maxCount: 1,
    rare: true,
    scanRadius: 38,
    scanSeconds: 3.4,
    look: { cD: 0x93403b, cB: 0xcf9e90, cFin: 0xa84d48, cEye: 0x0b0d10 },
  }),
];
